<?php
/** @var array $userSightings */
/** @var int|null $editingSightingID */
require_once __DIR__ . "/components/header.phtml";
?>
<?php if (isset($_SESSION['userID'])) { ?>
    <main class="card-container container card h-100 mt-3">
        <script src="/scripts/updateSighting.js"></script>
        <h4>Update Sighting</h4>
        <form method="post" enctype="multipart/form-data" action="/?page=update_sightings">
            <input type="hidden" name="csrf_token" value="<?= $_SESSION['csrf_token']; ?>">
            <input type="hidden" name="sightingID" id="sightingID">
            <div class="mb-3 text-center">
                <select id="userSightings" class="form-control">
                    <option disabled selected>--Choose a sighting--</option>
                    <?php foreach ($userSightings as $sighting): ?>
                        <option
                                value="<?= $sighting->getSightingID() ?>"
                                data-lat="<?= $sighting->getLatitude() ?>"
                                data-lng="<?= $sighting->getLongitude() ?>"
                                data-comment="<?= htmlspecialchars($sighting->getComment()) ?>"
                                data-photo="<?= htmlspecialchars($sighting->getPhotoURL()) ?>"
                        >
                            <?= htmlspecialchars($sighting->getInfo()) ?>
                        </option>
                    <?php endforeach; ?>
                </select>
            </div>
            <div id="formFields" style="display:none;">
                <div class="mb-3">
                    <img id="previewImage" src="" class="mb-3" style="width:200px;height:200px;">
                    <input type="file" name="photo_url" id="imageInput" accept=".jpg,.jpeg,.png"
                           class="form-control" alt="pet img">
                </div>

                <div class="mb-3">
                    <input type="number" name="latitude" id="latitude" class="form-control" required>
                </div>

                <div class="mb-3">
                    <input type="number" name="longitude" id="longitude" class="form-control" required>
                </div>

                <div class="mb-3">
                    <textarea name="comment" id="comment" class="form-control" required></textarea>
                </div>

                <button type="submit" name="updateSightingBtn" class="btn btn-primary mb-3">
                    Update Sighting
                </button>
            </div>
        </form>
    </main>
<?php } else { ?>
    <h3 class="mb-4">Invalid Access: You are not logged in</h3>
<?php } ?>
<?php require_once __DIR__ . ('/../views/components/footer.phtml') ?>
